export const ACTIONS={
    HAND:"HAND",
    SELECT:"SELECT",
    RECTANGLE:"RECTANGLE",
    DIAMOND:"DIAMOND",
    CIRCLE:"CIRCLE",
    LINE:"LINE",
    ARROWRIGHT:"ARROWRIGHT",
    SCRIBBLE:"SCRIBBLE",
    TEXT:"TEXT",
    IMAGE:"IMAGE",
    ERASER:"ERASER",
    ARROW:"ARROW"
}